const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const categories = [
  {
    id: "cat_electronics",
    name: "Electronics",
    slug: "electronics",
    description: "Cutting-edge tech for the future",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800",
    icon: "🔌",
    color: "#00F5FF",
    featured: true,
    sortOrder: 1,
  },
  {
    id: "cat_mobiles",
    name: "Mobiles",
    slug: "mobiles",
    description: "Flagship smartphones & accessories",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800",
    icon: "📱",
    color: "#7C3AED",
    featured: true,
    sortOrder: 2,
  },
  {
    id: "cat_gaming",
    name: "Gaming",
    slug: "gaming",
    description: "Next-gen gaming gear & consoles",
    image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800",
    icon: "🎮",
    color: "#FF00FF",
    featured: true,
    sortOrder: 3,
  },
  {
    id: "cat_fashion",
    name: "Fashion",
    slug: "fashion",
    description: "Premium styles from global brands",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=800",
    icon: "👗",
    color: "#F59E0B",
    featured: true,
    sortOrder: 4,
  },
  {
    id: "cat_home",
    name: "Home & Living",
    slug: "home-living",
    description: "Smart home & luxury decor",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800",
    icon: "🏠",
    color: "#22C55E",
    featured: true,
    sortOrder: 5,
  },
  {
    id: "cat_accessories",
    name: "Accessories",
    slug: "accessories",
    description: "Curated premium accessories",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
    icon: "⌚",
    color: "#00F5FF",
    featured: true,
    sortOrder: 6,
  },
  {
    id: "cat_luxury",
    name: "Luxury Collection",
    slug: "luxury",
    description: "Exclusive ultra-premium products",
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800",
    icon: "💎",
    color: "#F59E0B",
    featured: true,
    sortOrder: 7,
  },
  {
    id: "cat_gadgets",
    name: "Smart Gadgets",
    slug: "smart-gadgets",
    description: "IoT & AI-powered smart devices",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
    icon: "🤖",
    color: "#7C3AED",
    featured: true,
    sortOrder: 8,
  },
];

const brands = [
  { id: "brand_apple", name: "Apple", slug: "apple", featured: true },
  { id: "brand_samsung", name: "Samsung", slug: "samsung", featured: true },
  { id: "brand_sony", name: "Sony", slug: "sony", featured: true },
  { id: "brand_asus", name: "ASUS ROG", slug: "asus-rog", featured: true },
  { id: "brand_nvidia", name: "NVIDIA", slug: "nvidia", featured: true },
  { id: "brand_tesla", name: "Tesla", slug: "tesla", featured: true },
  { id: "brand_nothing", name: "Nothing", slug: "nothing", featured: true },
  { id: "brand_sennheiser", name: "Sennheiser", slug: "sennheiser", featured: true },
  { id: "brand_bo", name: "Bang & Olufsen", slug: "bang-olufsen", featured: true },
  { id: "brand_hasselblad", name: "Hasselblad", slug: "hasselblad", featured: true },
  { id: "brand_dyson", name: "Dyson", slug: "dyson", featured: true },
  { id: "brand_ap", name: "Audemars Piguet", slug: "audemars-piguet", featured: true },
  { id: "brand_nike", name: "Nike", slug: "nike", featured: true },
];

const products = [
  {
    id: "prod_001",
    name: "iPhone 17 Pro Max",
    slug: "iphone-17-pro-max",
    description: "Experience the pinnacle of smartphone technology with the iPhone 17 Pro Max. Featuring the A19 Bionic chip, ProMotion 4K display, and revolutionary computational photography.",
    shortDesc: "Apple's most powerful iPhone with A19 Bionic chip",
    sku: "APL-IP17PM-256",
    price: 159999,
    offerPrice: 149999,
    stock: 42,
    categoryId: "cat_mobiles",
    brandId: "brand_apple",
    images: ["https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=800"],
    tags: ["apple", "iphone", "smartphone", "flagship"],
    featured: true,
    trending: true,
    newArrival: true,
    luxuryItem: false,
    gstRate: 18,
    weight: 0.228,
    specifications: {
      Chip: "A19 Bionic",
      Display: "6.9-inch ProMotion OLED",
      Camera: "200MP Main + 48MP Ultra Wide + 12MP Telephoto",
      Battery: "4685 mAh",
      OS: "iOS 19",
      Storage: "256GB",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_002",
    name: "Samsung Galaxy S25 Ultra",
    slug: "samsung-galaxy-s25-ultra",
    description: "The Samsung Galaxy S25 Ultra redefines what a smartphone can do with its integrated S Pen, Snapdragon 8 Elite chip, and 200MP camera system.",
    shortDesc: "Samsung's ultimate flagship with built-in S Pen",
    sku: "SAM-GS25U-256",
    price: 134999,
    offerPrice: 124999,
    stock: 28,
    categoryId: "cat_mobiles",
    brandId: "brand_samsung",
    images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800"],
    tags: ["samsung", "galaxy", "spen", "android"],
    featured: true,
    trending: true,
    newArrival: false,
    luxuryItem: false,
    gstRate: 18,
    weight: 0.218,
    specifications: {
      Chip: "Snapdragon 8 Elite",
      Display: "6.9-inch Dynamic AMOLED 2X",
      Camera: "200MP + 50MP + 10MP + 12MP",
      Battery: "5000 mAh",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_003",
    name: "Sony WH-1000XM6",
    slug: "sony-wh-1000xm6",
    description: "Industry-leading noise canceling headphones with 30-hour battery life, LDAC support, and premium audio quality.",
    shortDesc: "Best-in-class noise canceling wireless headphones",
    sku: "SNY-WH1000XM6-B",
    price: 34990,
    offerPrice: 29990,
    stock: 87,
    categoryId: "cat_accessories",
    brandId: "brand_sony",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
    tags: ["sony", "headphones", "anc", "audio"],
    featured: true,
    trending: false,
    newArrival: true,
    luxuryItem: false,
    gstRate: 18,
    weight: 0.250,
    specifications: {
      "Driver Size": "40mm",
      "Frequency Response": "4Hz - 40kHz",
      "Battery Life": "30 hours",
      Connection: "Bluetooth 5.3",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_004",
    name: "MacBook Pro 16\" M4 Max",
    slug: "macbook-pro-16-m4-max",
    description: "The most powerful MacBook Pro ever with M4 Max chip, delivering extraordinary CPU and GPU performance with up to 128GB unified memory.",
    shortDesc: "Apple M4 Max powered professional laptop",
    sku: "APL-MBP16-M4MAX",
    price: 399900,
    offerPrice: 379900,
    stock: 15,
    categoryId: "cat_electronics",
    brandId: "brand_apple",
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800"],
    tags: ["apple", "macbook", "laptop", "m4"],
    featured: true,
    trending: true,
    newArrival: true,
    luxuryItem: true,
    gstRate: 18,
    weight: 2.14,
    specifications: {
      Chip: "Apple M4 Max (14-core CPU, 32-core GPU)",
      Display: "16.2-inch Liquid Retina XDR",
      Memory: "64GB Unified Memory",
      Storage: "1TB SSD",
      Battery: "100Wh",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_005",
    name: "ASUS ROG Ally X",
    slug: "asus-rog-ally-x",
    description: "The ultimate handheld gaming PC with AMD Ryzen Z2 Extreme processor, 120Hz display, and 24GB RAM for desktop-class gaming anywhere.",
    shortDesc: "Handheld gaming PC with desktop-class performance",
    sku: "ASUS-ROGALLYX-1TB",
    price: 89999,
    offerPrice: 79999,
    stock: 31,
    categoryId: "cat_gaming",
    brandId: "brand_asus",
    images: ["https://images.unsplash.com/photo-1593640495253-23196b27a87f?w=800"],
    tags: ["asus", "rog", "gaming", "handheld"],
    featured: true,
    trending: true,
    newArrival: false,
    luxuryItem: false,
    gstRate: 18,
    weight: 0.678,
    specifications: {
      Processor: "AMD Ryzen Z2 Extreme",
      Display: "7-inch FHD IPS 120Hz",
      RAM: "24GB LPDDR5x",
      Storage: "1TB NVMe SSD",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_006",
    name: "Apple Watch Ultra 3",
    slug: "apple-watch-ultra-3",
    description: "The most capable and durable Apple Watch ever made. Built for extreme environments with Action button, GPS, and Emergency SOS.",
    shortDesc: "Ultimate adventure smartwatch by Apple",
    sku: "APL-AWU3-49MM",
    price: 89900,
    offerPrice: 84900,
    stock: 22,
    categoryId: "cat_accessories",
    brandId: "brand_apple",
    images: ["https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800"],
    tags: ["apple", "watch", "smartwatch", "ultra"],
    featured: false,
    trending: true,
    newArrival: true,
    luxuryItem: true,
    gstRate: 18,
    weight: 0.061,
    specifications: {
      Case: "49mm Titanium",
      Display: "Always-On Retina LTPO3",
      Battery: "Up to 36 hours",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_007",
    name: "Sony PS5 Pro",
    slug: "sony-ps5-pro",
    description: "The PlayStation 5 Pro delivers extraordinary 8K gaming performance with enhanced GPU, ray tracing, and PlayStation Spectral Super Resolution.",
    shortDesc: "Sony's most powerful PlayStation console",
    sku: "SNY-PS5PRO-1TB",
    price: 64999,
    offerPrice: 59999,
    stock: 8,
    categoryId: "cat_gaming",
    brandId: "brand_sony",
    images: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800"],
    tags: ["sony", "playstation", "ps5", "gaming"],
    featured: true,
    trending: true,
    newArrival: false,
    luxuryItem: false,
    gstRate: 18,
    weight: 3.2,
    specifications: {
      CPU: "AMD Zen 2 Enhanced",
      GPU: "45 TFLOPS Enhanced RDNA",
      Storage: "1TB Ultra-HD SSD",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_008",
    name: "NVIDIA RTX 5090",
    slug: "nvidia-rtx-5090",
    description: "The NVIDIA GeForce RTX 5090 is the most powerful graphics card ever made, featuring 32,768 CUDA cores and 32GB GDDR7 memory.",
    shortDesc: "World's fastest consumer GPU",
    sku: "NVD-RTX5090-32G",
    price: 249999,
    offerPrice: 239999,
    stock: 4,
    categoryId: "cat_electronics",
    brandId: "brand_nvidia",
    images: ["https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800"],
    tags: ["nvidia", "rtx", "gpu", "gaming"],
    featured: true,
    trending: true,
    newArrival: true,
    luxuryItem: true,
    gstRate: 18,
    weight: 2.1,
    specifications: {
      "CUDA Cores": "32,768",
      Memory: "32GB GDDR7",
      Bus: "512-bit",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_009",
    name: "Tesla Model S Plaid (India Edition)",
    slug: "tesla-model-s-plaid-india",
    description: "The Tesla Model S Plaid India Edition redefines high-performance luxury EVs. With custom ground clearance for Indian roads, a tri-motor setup producing 1020 HP, 0-100 km/h in 2.1s, and custom luxury wood veneers.",
    shortDesc: "Tri-motor electric hyper-sedan with 1020 HP",
    sku: "TSL-MSPLAID-IND",
    price: 15000000,
    offerPrice: 14500000,
    stock: 2,
    categoryId: "cat_luxury",
    brandId: "brand_tesla",
    images: ["https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800"],
    tags: ["tesla", "ev", "luxury", "hypercar", "electric"],
    featured: true,
    trending: true,
    newArrival: true,
    luxuryItem: true,
    gstRate: 5,
    weight: 2162,
    specifications: {
      Power: "1,020 hp",
      Range: "637 km (EPA est.)",
      Drivetrain: "Tri-Motor All-Wheel Drive",
      "0-100 km/h": "2.1 seconds",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_010",
    name: "Apple Vision Pro 2",
    slug: "apple-vision-pro-2",
    description: "Welcome to the era of spatial computing. Apple Vision Pro 2 seamlessly blends digital content with your physical space, powered by dual M3 & R2 chips, dual-micro-OLED 4K displays, and highly responsive hand, eye, and voice tracking.",
    shortDesc: "Apple's next-gen premium spatial computer",
    sku: "APL-AVP2-1TB",
    price: 329900,
    offerPrice: 319900,
    stock: 7,
    categoryId: "cat_electronics",
    brandId: "brand_apple",
    images: ["https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800"],
    tags: ["apple", "vision", "vr", "ar", "spatial"],
    featured: true,
    trending: true,
    newArrival: true,
    luxuryItem: true,
    gstRate: 18,
    weight: 0.612,
    specifications: {
      Chips: "Apple M3 & R2",
      Displays: "Dual micro-OLED 23 million pixels",
      Sensors: "12 cameras, 5 sensors, 6 mics",
      Storage: "1TB",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_011",
    name: "Nothing Phone (3) Space Edition",
    slug: "nothing-phone-3-space-edition",
    description: "The Nothing Phone (3) Space Edition breaks boundaries with its glowing glyph-interface, semi-transparent ceramic rear panel, Snapdragon 8s Gen 4 chip, and a pristine 144Hz LTPO OLED display.",
    shortDesc: "Minimalist glowing design with top-tier specifications",
    sku: "NOT-PH3-SPACE",
    price: 64999,
    offerPrice: 59999,
    stock: 45,
    categoryId: "cat_mobiles",
    brandId: "brand_nothing",
    images: ["https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=800"],
    tags: ["nothing", "phone3", "glyph", "android"],
    featured: false,
    trending: true,
    newArrival: true,
    luxuryItem: false,
    gstRate: 18,
    weight: 0.194,
    specifications: {
      Processor: "Snapdragon 8s Gen 4",
      Display: "6.7-inch LTPO OLED 144Hz",
      Battery: "5050 mAh",
      Glyph: "24 Zone LED",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_012",
    name: "Sennheiser HE-1 Orpheus",
    slug: "sennheiser-he-1-orpheus",
    description: "The Sennheiser HE-1 Orpheus is the world's most premium electrostatic headphone system. Crafted with Carrara marble housing, integrated tube amplifiers that rise automatically on startup, and platinum-vaporized diaphragms.",
    shortDesc: "The undisputed reference headphone system",
    sku: "SNH-HE1-ORPH",
    price: 4500000,
    offerPrice: 4200000,
    stock: 1,
    categoryId: "cat_luxury",
    brandId: "brand_sennheiser",
    images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800"],
    tags: ["sennheiser", "orpheus", "he1", "headphones", "audiophile"],
    featured: true,
    trending: false,
    newArrival: false,
    luxuryItem: true,
    gstRate: 18,
    weight: 25.0,
    specifications: {
      Type: "Electrostatic, Open-back",
      Amplifier: "Integrated Carrara Marble Tube Amp",
      "Frequency Range": "8 Hz to over 100 kHz",
      "THD": "0.01% at 1 kHz, 100 dB SPL",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_013",
    name: "Bang & Olufsen Beolab 90",
    slug: "bang-olufsen-beolab-90",
    description: "The Bang & Olufsen Beolab 90 is the ultimate digital active loudspeaker. Delivering 8,200 watts of power per speaker, 18 premium drivers, and active room compensation to adapt perfectly to any living space.",
    shortDesc: "Ultra-premium active loudspeaker with 8,200W",
    sku: "BO-BL90-PAIR",
    price: 8500000,
    offerPrice: 8200000,
    stock: 1,
    categoryId: "cat_luxury",
    brandId: "brand_bo",
    images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800"],
    tags: ["bang-olufsen", "speaker", "audio", "luxury", "home-theater"],
    featured: true,
    trending: true,
    newArrival: false,
    luxuryItem: true,
    gstRate: 18,
    weight: 137.0,
    specifications: {
      Power: "8,200 Watts per speaker",
      Drivers: "18 scan-speak drivers",
      "Active Compensation": "Active Room Compensation technology",
      Design: "360-degree acoustic performance",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_014",
    name: "Dyson 360 Vis Nav",
    slug: "dyson-360-vis-nav",
    description: "The most powerful robot vacuum with twice the suction of any other. Dyson 360 Vis Nav features a panoramic 360 camera, smart mapping, side-edge actuator, and Dyson Hyperdymium motor running up to 110,000 RPM.",
    shortDesc: "Dyson's most powerful robotic vacuum cleaner",
    sku: "DYS-360VISNAV",
    price: 119900,
    offerPrice: 109900,
    stock: 12,
    categoryId: "cat_home",
    brandId: "brand_dyson",
    images: ["https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?w=800"],
    tags: ["dyson", "vacuum", "robot", "smart-home"],
    featured: false,
    trending: true,
    newArrival: true,
    luxuryItem: false,
    gstRate: 18,
    weight: 3.2,
    specifications: {
      Suction: "65 AW Max Suction Power",
      Sensor: "360 Panoramic Vision System",
      Motor: "Dyson Hyperdymium Motor",
      Runtime: "Up to 50 minutes",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_015",
    name: "Hasselblad H6D-100c",
    slug: "hasselblad-h6d-100c",
    description: "Capture reality in absolute precision with the Hasselblad H6D-100c medium format camera. Armed with a massive 100MP CMOS sensor, 15 stops of dynamic range, and Hasselblad Natural Colour Solution (HNCS) for perfect skin tones.",
    shortDesc: "100 Megapixel medium format professional camera",
    sku: "HAS-H6D100C",
    price: 2800000,
    offerPrice: 2650000,
    stock: 3,
    categoryId: "cat_luxury",
    brandId: "brand_hasselblad",
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800"],
    tags: ["hasselblad", "camera", "medium-format", "photography", "professional"],
    featured: true,
    trending: false,
    newArrival: false,
    luxuryItem: true,
    gstRate: 18,
    weight: 2.1,
    specifications: {
      Sensor: "100MP CMOS (53.4 x 40.0mm)",
      DynamicRange: "15 stops",
      Video: "4K UHD video capability",
      Color: "Hasselblad Natural Colour Solution",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_016",
    name: "NovaMart Quantum 1 Concept Laptop",
    slug: "novamart-quantum-1",
    description: "Welcome to the absolute future. The NovaMart Quantum 1 Concept Laptop features a transparent holographic OLED display, dual-screen projection keyboard, next-gen high-efficiency battery, and an experimental AI coprocessor for ultra-secure computing.",
    shortDesc: "Holographic display concept workstation",
    sku: "NVM-QNT1-CONCPT",
    price: 999999,
    offerPrice: 949999,
    stock: 5,
    categoryId: "cat_luxury",
    brandId: "brand_nvidia",
    images: ["https://images.unsplash.com/photo-1618424181497-157f25b6ddd5?w=800"],
    tags: ["novamart", "quantum", "laptop", "holographic", "concept"],
    featured: true,
    trending: true,
    newArrival: true,
    luxuryItem: true,
    gstRate: 18,
    weight: 1.8,
    specifications: {
      Display: "15.6-inch Holographic Transparent OLED",
      Coprocessor: "QuantumAI-V1 Chipset",
      RAM: "128GB LPDDR6",
      OS: "NovaOS Quantum Edition",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_017",
    name: "Audemars Piguet Royal Oak Concept",
    slug: "ap-royal-oak-concept",
    description: "The Audemars Piguet Royal Oak Concept is a masterpiece of haute horlogerie. It features a hand-wound manufacture caliber, flying tourbillon, titanium case, and a futuristic open-worked dial showing the mechanical heart.",
    shortDesc: "Masterpiece of futuristic luxury watchmaking with flying tourbillon",
    sku: "AP-ROC-TITANIUM",
    price: 18500000,
    offerPrice: 17900000,
    stock: 2,
    categoryId: "cat_fashion",
    brandId: "brand_ap",
    images: ["https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800"],
    tags: ["ap", "watch", "luxury", "fashion", "tourbillon"],
    featured: true,
    trending: false,
    newArrival: true,
    luxuryItem: true,
    gstRate: 18,
    weight: 0.145,
    specifications: {
      Case: "44mm Sandblasted Titanium",
      Movement: "Hand-wound Calibre 2964",
      PowerReserve: "72 hours",
      WaterResistance: "50m",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_018",
    name: "Nike Adapt BB 3.0 Self-Lacing Sneakers",
    slug: "nike-adapt-bb-3",
    description: "Experience the future of footwear with the Nike Adapt BB 3.0. Features power-lacing that molds to your foot for a perfect fit, customizable LED lights, and wireless charging. Powered by the Nike Adapt app to adjust fit and colors dynamically.",
    shortDesc: "Futuristic self-lacing basketball shoes with app integration",
    sku: "NKE-ADAPT-BB3",
    price: 34999,
    offerPrice: 29999,
    stock: 15,
    categoryId: "cat_fashion",
    brandId: "brand_nike",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800"],
    tags: ["nike", "sneakers", "shoes", "self-lacing", "adapt"],
    featured: true,
    trending: true,
    newArrival: true,
    luxuryItem: false,
    gstRate: 18,
    weight: 0.85,
    specifications: {
      Technology: "Nike FitAdapt Power-Lacing",
      Connectivity: "Bluetooth 5.0",
      BatteryLife: "Up to 14 days per charge",
      Charging: "Qi Wireless Charging Pad included",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_019",
    name: "Unitree Go2 Pro AI Robot Dog",
    slug: "unitree-go2-pro-robot-dog",
    description: "The Unitree Go2 Pro is an advanced AI-powered quadruped robot. Equipped with 4D ultra-wide LiDAR, GPT-enabled voice assistant, autonomous obstacle avoidance, and dynamic locomotion capabilities including jumps and flips.",
    shortDesc: "Advanced AI-powered quadruped robot with LiDAR",
    sku: "UNT-GO2-PRO",
    price: 299900,
    offerPrice: 279900,
    stock: 5,
    categoryId: "cat_gadgets",
    brandId: "brand_nvidia",
    images: ["https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800"],
    tags: ["robot", "ai", "companion", "gadget", "quadruped"],
    featured: true,
    trending: true,
    newArrival: true,
    luxuryItem: true,
    gstRate: 18,
    weight: 15.0,
    specifications: {
      Sensor: "4D Ultra-wide LiDAR",
      CPU: "NVIDIA Jetson Orin Nano",
      Battery: "8000 mAh (1.5 - 2 hours runtime)",
      Speed: "Max 3.5 m/s",
    },
    status: "ACTIVE",
  },
  {
    id: "prod_020",
    name: "NovaRing Gen 4 Smart Ring",
    slug: "novaring-gen-4",
    description: "The NovaRing Gen 4 is the ultimate health and sleep tracker wrapped in a sleek titanium band. Monitor your heart rate, SpO2, sleep stages, skin temperature, and daily activity with medical-grade accuracy. Fully waterproof and features 7-day battery life.",
    shortDesc: "Sleek titanium health and sleep tracking smart ring",
    sku: "NVM-RING4-TI",
    price: 19999,
    offerPrice: 17999,
    stock: 60,
    categoryId: "cat_gadgets",
    brandId: "brand_nothing",
    images: ["https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800"],
    tags: ["smart-ring", "wearable", "health", "nothing", "tracker"],
    featured: false,
    trending: true,
    newArrival: true,
    luxuryItem: false,
    gstRate: 18,
    weight: 0.004,
    specifications: {
      Material: "Fighter-grade Titanium",
      Sensors: "PPG, Accelerometer, Temperature, SpO2",
      Waterproof: "Up to 100m (10 ATM)",
      Battery: "Up to 7 days",
    },
    status: "ACTIVE",
  },
];

async function main() {
  console.log("Seeding started...");

  // Seed Categories
  for (const cat of categories) {
    await prisma.category.upsert({
      where: { id: cat.id },
      update: cat,
      create: cat,
    });
  }
  console.log("Categories seeded successfully.");

  // Seed Brands
  for (const brand of brands) {
    await prisma.brand.upsert({
      where: { id: brand.id },
      update: brand,
      create: brand,
    });
  }
  console.log("Brands seeded successfully.");

  // Seed Products
  for (const prod of products) {
    const { categoryId, brandId, ...productData } = prod;
    await prisma.product.upsert({
      where: { id: prod.id },
      update: {
        ...productData,
        category: { connect: { id: categoryId } },
        ...(brandId ? { brand: { connect: { id: brandId } } } : {}),
      },
      create: {
        ...productData,
        category: { connect: { id: categoryId } },
        ...(brandId ? { brand: { connect: { id: brandId } } } : {}),
      },
    });
  }
  console.log("Products seeded successfully.");

  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
